apiVersion: apps/v1
kind: Deployment
metadata:
  name: starbucks-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: starbucks-app
  template:
    metadata:
      labels:
        app: starbucks-app
    spec:
      containers:
      - name: starbucks-app
        image: pankajt775/starbucks-app:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: starbucks-service
spec:
  selector:
    app: starbucks-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
